name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # PREPARE DOCKER ENVIRONMENT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
      
      # BUILD AND PUSH DOCKER IMAGES
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: 
            - rodcordeiro/banky:latest
            - rodcordeiro/banky:$(date +%s)