name: TEST

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the value
        id: step_one
        run: |
          version=$(jq '.version' package.json)
          echo "PKG_VERSION=$version" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          version=$(echo $str | sed "s/\"//g")
          printf 'rodcordeiro/banky:%s\n' "$version" # This will output 'yellow'