name: TEST

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the value
        id: step_one
        run: |

          version = $(jq '.version' package.json)
          echo "PKG_VERSION=$version" # >> "$GITHUB_ENV"
