name: TEST

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the version value
        id: version
        run: |
          version=$(jq '.version' package.json | sed "s/\"//g")
          echo "PKG_VERSION=v$version" >> "$GITHUB_OUTPUT"
      - name: Use the value
        id: step_two
        run: |
         rodcordeiro/banky:latest,rodcordeiro/banky:${{ steps.version.outputs.PKG_VERSION }}